# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(max_length=255)),
                ('desc', models.TextField()),
                ('cost', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Type.Type')),
            ],
        ),
    ]
