# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('requiredxp', models.BigIntegerField()),
            ],
        ),
    ]
