# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dmg', models.BigIntegerField()),
                ('armor', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('carry', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player_unit',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unit.Unit'),
        ),
    ]
