# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='multipleir',
            new_name='multiplier',
        ),
    ]
